name: airv2x_HEAL_collab_camera
active_sensors: &id002
- cam
collaborators:
- vehicle
- rsu
ego_type: vehicle
bevcam_fov: 110
yaml_parser: load_airv2x_params
train_params:
  batch_size: 1
  epoches: 1
  eval_freq: 0
  save_freq: 1
  grad_clip: 1.0
  max_cav:
    vehicle: 4
    rsu: 3
    drone: 0
device: cuda
train: true
root_dir: /data1/wangyh/airdata/AirV2X-Perception/train/train/
validate_dir: /data1/wangyh/airdata/AirV2X-Perception/val/val/
test_dir: /data/wangyh/test/
num_class: 7
num_anchor: 2
correct_lidar_coordinate_system: true
data_filter:
  drop_empty_lidar_agents: false
  keep_ego_when_empty: true
  min_lidar_points: 0
  max_total_cavs: 2
  empty_lidar_log_cap: 0
task: det
seg_branch: both
seg_hw: 512
seg_res: 0.25
dynamic_class: 7
static_class: 3
fusion:
  core_method: IntermediateFusionDatasetAirv2x
  args:
    proj_first: true
    veh_grid_conf: &id003
      xbound:
      - -140.8
      - 140.8
      - 0.8
      ybound:
      - -40
      - 40
      - 0.8
      zbound:
      - -10
      - 10
      - 20.0
      ddiscr:
      - 2
      - 50
      - 48
      mode: LID
    veh_data_aug_conf: &id004
      resize_lim:
      - 0.65
      - 0.7
      final_dim:
      - 360
      - 640
      rot_lim:
      - 0
      - 0
      H: 720
      W: 1280
      rand_flip: false
      bot_pct_lim:
      - 0.0
      - 0.05
    rsu_grid_conf: &id005
      xbound:
      - -140.8
      - 140.8
      - 0.8
      ybound:
      - -40
      - 40
      - 0.8
      zbound:
      - -30
      - 30
      - 60.0
      ddiscr:
      - 2
      - 50
      - 48
      mode: LID
    rsu_data_aug_conf: &id006
      resize_lim:
      - 0.65
      - 0.7
      final_dim:
      - 360
      - 640
      rot_lim:
      - 0
      - 0
      H: 720
      W: 1280
      rand_flip: false
      bot_pct_lim:
      - 0.0
      - 0.05
    drone_grid_conf: &id007
      xbound:
      - -140.8
      - 140.8
      - 0.8
      ybound:
      - -40
      - 40
      - 0.8
      zbound:
      - -150
      - -6
      - 144
      ddiscr:
      - 6
      - 150
      - 144
      mode: UD
    drone_data_aug_conf: &id008
      resize_lim:
      - 0.65
      - 0.7
      final_dim:
      - 360
      - 640
      rot_lim:
      - -3.6
      - 3.6
      H: 720
      W: 1280
      rand_flip: false
      bot_pct_lim:
      - 0.0
      - 0.05
data_augment:
- NAME: random_world_flip
  ALONG_AXIS_LIST:
  - x
- NAME: random_world_rotation
  WORLD_ROT_ANGLE:
  - -0.78539816
  - 0.78539816
- NAME: random_world_scaling
  WORLD_SCALE_RANGE:
  - 0.95
  - 1.05
preprocess:
  core_method: SpVoxelPreprocessor
  ego_type: vehicle
  args:
    voxel_size:
    - 0.8
    - 0.8
    - 4
    max_points_per_voxel: 32
    max_voxel_train: 32000
    max_voxel_test: 70000
  cav_lidar_range: &id001
  - -140.8
  - -40
  - -3
  - 140.8
  - 40
  - 1
postprocess:
  core_method: VoxelPostprocessor
  ego_type: vehicle
  anchor_args:
    cav_lidar_range: *id001
    l: 3.9
    w: 1.6
    h: 1.56
    r:
    - 0
    - 90
    feature_stride: 2
    num: 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.2
    obj_threshold: 0.2
  order: hwl
  max_num: 300
  nms_thresh: 0.15
model:
  core_method: airv2x_heal
  args:
    collaborators:
    - vehicle
    - rsu
    active_sensors: *id002
    device: cuda
    train: true
    proj_first: true
    supervise_single: false
    backbone_fix:
    - rsu
    - drone
    vehicle:
      modalities:
      - cam
      lidar:
        voxel_size:
        - 0.8
        - 0.8
        - 4
        lidar_range:
        - -140.8
        - -40
        - -3
        - 140.8
        - 40
        - 1
        compression: 0
        backbone_fix: false
        pillar_vfe:
          use_norm: true
          with_distance: false
          use_absolute_xyz: true
          num_filters:
          - 64
        point_pillar_scatter:
          num_features: 64
      cam:
        grid_conf: *id003
        data_aug_conf: *id004
        img_downsample: 8
        img_features: 64
        bevout_feature: 64
        camera_encoder: Resnet101
        use_depth_gt: true
        depth_supervision: false
    rsu:
      modalities:
      - cam
      lidar:
        voxel_size:
        - 0.8
        - 0.8
        - 60
        lidar_range:
        - -140.8
        - -40
        - -30
        - 140.8
        - 40
        - 30
        compression: 0
        backbone_fix: false
        pillar_vfe:
          use_norm: true
          with_distance: false
          use_absolute_xyz: true
          num_filters:
          - 64
        point_pillar_scatter:
          num_features: 64
      cam:
        grid_conf: *id005
        data_aug_conf: *id006
        img_downsample: 8
        img_features: 64
        bevout_feature: 64
        camera_encoder: Resnet101
        use_depth_gt: true
        depth_supervision: false
    drone:
      modalities:
      - cam
      lidar:
        voxel_size:
        - 0.8
        - 0.8
        - 144
        lidar_range:
        - -140.8
        - -40
        - -150
        - 140.8
        - 40
        - -6
        compression: 0
        backbone_fix: false
        pillar_vfe:
          use_norm: true
          with_distance: false
          use_absolute_xyz: true
          num_filters:
          - 64
        point_pillar_scatter:
          num_features: 64
      cam:
        grid_conf: *id007
        data_aug_conf: *id008
        img_downsample: 8
        img_features: 64
        bevout_feature: 64
        camera_encoder: Resnet101
        use_depth_gt: true
        depth_supervision: false
    modality_fusion:
      base_bev_backbone:
        layer_nums:
        - 3
        layer_strides:
        - 2
        num_filters:
        - 64
      compression: 0
      shrink_header:
        use: true
        kernal_size:
        - 3
        stride:
        - 1
        padding:
        - 1
        dim:
        - 192
        input_dim: 144
    fusion_backbone:
      resnext: true
      layer_nums:
      - 3
      - 4
      - 6
      layer_strides:
      - 1
      - 2
      - 2
      num_filters:
      - 40
      - 80
      - 160
      upsample_strides:
      - 1
      - 2
      - 4
      num_upsample_filter:
      - 48
      - 48
      - 48
      anchor_number: 2
      use_mamba: false
      mamba_window: 4
      mamba_kernel: 3
    task: det
    seg_branch: both
    seg_hw: 512
    in_head: 192
    anchor_number: 2
    num_class: 7
    dynamic_class: 7
    static_class: 3
    cav_range: *id001
    seg_res: 0.25
    obj_head: true
loss:
  det:
    core_method: point_pillar_loss_multiclass
    args:
      cls_weight: 1.0
      reg: 2.0
      num_class: 7
      alpha: 0.25
      gamma: 2.0
      flow_weight: 1.0
  seg:
    core_method: vanilla_seg_loss
    args:
      seg_branch: both
      d_weights:
      - 200.0
      - 200.0
      - 75.0
      - 200.0
      - 200.0
      - 200.0
      s_weights: 50.0
      l_weights: 8.0
      d_coe: 2.0
      s_coe: 0.0
optimizer:
  core_method: Adam
  lr: 5.0e-05
  args:
    eps: 1e-10
    weight_decay: 1e-4
lr_scheduler:
  core_method: multistep
  gamma: 0.1
  step_size:
  - 10
  - 25
